### ISSUE TITLE
[Feature request] disable `f` keys and other keys that one can press accidentally during the game

### ISSUE THREAD

**Issue by Sentero-esp12** [artyompal/lichess_keyboard#5]
Pressing `f` flips the board, and it's probably better to disable it or create an option to disable the default shortcuts

**Comment by artyompal** [comment]
Is it really necessary? This extension only handles keystrokes when the mouse pointer is hovering on the board. If the cursor is somewhere outside, I assume that you don't intend to move a piece, do you?

It could catch all keystrokes globally, but this would break the chat, search bar and so on.

**Comment by Sentero-esp12** [comment]
Many users complained about this, so it seems better to disable it, also `f` flips the board even while hovering over the board. With the chat, you could check whether the focus is on the chat or something similar (I don't remember exactly, but I think you could check Lichess kb input and multipremove extensions for how it's done) and then only prevent some events

**Comment by artyompal** [comment]
For me, `f` doesn't flip the board while hovering over the board, It's possible to handle keys globally but i see no point since you're probably not trying to move anything if the cursor is not on the board.

**Comment by Sentero-esp12** [comment]
Do you have `f` set to something?

**Comment by artyompal** [comment]
Yes. Ok, so you mean that all keys should be intercepted when the cursor is hovering over the board?

**Comment by Sentero-esp12** [comment]
Also let's say if someone has `s` for a piece, they move a piece and then accidentally their cursor leaves the board. It then might open the search panel. As a suggestion, only keypresses for which the `keydown` event happened outside the board should execute native Lichess features

**Comment by artyompal** [comment]
This is fixed in c840803. All key events are filtered when mouse is hovering the boards
